#COBUMMFO-4762# Коментар: back COBUMMFO-4762 Open in IDE c:\TeamCity\buildAgent\work\28a7da1e4ad7f6dd\barsroot\deposit\dialog\depositbfrowcorrection.aspx.cs(209, 0): error CS0103: The name 'textIdCode' does not exist in the current context c:\TeamCity\buildAgent\work\28a7da1e4ad7f6dd\barsroot\deposit\dialog\depositbfrowcorrection.aspx.cs(211, 0): error CS0103: The name 'ddAccType' does not exist in the current context